<?php

namespace CustomsReview\Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class MyGroupProxy extends \MyGroup implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }
    
    
    public function ID()
    {
        $this->__load();
        return parent::ID();
    }

    public function Title()
    {
        $this->__load();
        return parent::Title();
    }

    public function PersianTitle()
    {
        $this->__load();
        return parent::PersianTitle();
    }

    public function RTitle()
    {
        $this->__load();
        return parent::RTitle();
    }

    public function Description()
    {
        $this->__load();
        return parent::Description();
    }

    public function User()
    {
        $this->__load();
        return parent::User();
    }

    public function AlarmFree()
    {
        $this->__load();
        return parent::AlarmFree();
    }

    public function AddAlarmFree($AlarmFree)
    {
        $this->__load();
        return parent::AddAlarmFree($AlarmFree);
    }

    public function ConfigAlarm()
    {
        $this->__load();
        return parent::ConfigAlarm();
    }

    public function AddConfigAlarm(\ConfigAlarm $ConfigAlarm)
    {
        $this->__load();
        return parent::AddConfigAlarm($ConfigAlarm);
    }

    public function MailGive()
    {
        $this->__load();
        return parent::MailGive();
    }

    public function MailGet()
    {
        $this->__load();
        return parent::MailGet();
    }

    public function MailReceive()
    {
        $this->__load();
        return parent::MailReceive();
    }

    public function MailSend()
    {
        $this->__load();
        return parent::MailSend();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'ID', 'Title', 'PersianTitle', 'Description', 'User', 'AlarmFree', 'ConfigAlarm', 'MailGive', 'MailGet', 'MailReceive', 'MailSend');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}